# spring boot 基础配置
server:
  port: 18080
spring:
  application:
    name: itcast-haoke-manage-api-server

# dubbo 配置
dubbo:
  application:
    name: dubbo-consumer-haoke-manage # 应用名称
  registry: # zk注册中心
    address: zookeeper://192.168.100.134:2181
    client: zkclient
# 日志级别
logging:
  level:
    root: DEBUG

# 阿里云 oss参数配置
aliyun:
  endpoint: oss-cn-qingdao.aliyuncs.com
  accessKeyId: LTAIfC7fUsPj7Rfq
  accessKeySecret: c2Vo3q1AmivtY8lxFnfsCfkO2c2HCkaliyun
  bucketName: itcast-haoke
  urlPrefix: http://itcast-haoke.oss-cn-qingdao.aliyuncs.com/