server:
  port: 18081
spring:
  application:
    name: itcast-haoke-im
  data:
    mongodb:
      uri: mongodb://192.168.100.134:27017/testdb
rocketmq:
  name-server: 192.168.100.134:9876
  producer:
    group: haoke-im-websocket-group